import type { Category } from '../model/types';

export const mockCategories: Category[] = [
  {
    id: 'inc-1',
    userId: 'demo',
    name: '급여',
    type: 'income',
    icon: 'wallet',
    color: '#2563EB',
    sortOrder: 1,
  },
  {
    id: 'inc-2',
    userId: 'demo',
    name: '부수입',
    type: 'income',
    icon: 'trending-up',
    color: '#2563EB',
    sortOrder: 2,
  },
  {
    id: 'exp-1',
    userId: 'demo',
    name: '식비',
    type: 'expense',
    icon: 'restaurant',
    color: '#EF4444',
    sortOrder: 1,
  },
  {
    id: 'exp-2',
    userId: 'demo',
    name: '교통',
    type: 'expense',
    icon: 'directions-car',
    color: '#EF4444',
    sortOrder: 2,
  },
  {
    id: 'exp-3',
    userId: 'demo',
    name: '쇼핑',
    type: 'expense',
    icon: 'shopping-bag',
    color: '#EF4444',
    sortOrder: 3,
  },
  {
    id: 'exp-4',
    userId: 'demo',
    name: '주거',
    type: 'expense',
    icon: 'home',
    color: '#EF4444',
    sortOrder: 4,
  },
  {
    id: 'exp-5',
    userId: 'demo',
    name: '기타',
    type: 'expense',
    icon: 'more-horiz',
    color: '#EF4444',
    sortOrder: 5,
  },
];
